chore: 🤖 update version in github actions

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -46,7 +46,7 @@ jobs:
       ENABLE_LIGHTBOX: ${{ vars.ENABLE_LIGHTBOX }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       - name: Detect package manager
         id: detect-package-manager
         run: |
@@ -65,7 +65,7 @@ jobs:
             exit 1
           fi
       - name: Setup Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: '20.18.1'
           cache: ${{ steps.detect-package-manager.outputs.manager }}
@@ -77,12 +77,21 @@ jobs:
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
         working-directory: ${{ env.BUILD_PATH }}
       - name: Build with Astro
-        run: npm run build
+        run: |
+          npm run build || exit 1
+        working-directory: ${{ env.BUILD_PATH }}
+      - name: Check dist directory
+        run: |
+          if [ ! -d "${{ env.BUILD_PATH }}/dist" ]; then
+            echo "Dist directory not found"
+            exit 1
+          fi
         working-directory: ${{ env.BUILD_PATH }}
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v2
+        uses: actions/upload-pages-artifact@v3
         with:
           path: ${{ env.BUILD_PATH }}/dist
+          name: github-pages
 
   deploy:
     environment:
@@ -94,4 +103,4 @@ jobs:
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v2
+        uses: actions/deploy-pages@v4
